name: CI Pipeline

on:
  pull_request:

jobs:
  build:
    runs-on: gitea-runner
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with: { dotnet-version: '8.0.x' }
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet test --no-build

  quality:
    runs-on: gitea-runner
    needs: build               # ждёт, пока build закончится
    continue-on-error: true    # падения здесь не сломают статус overall
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with: { dotnet-version: '8.0.x' }
      - run: dotnet restore
      - run: dotnet format --verify-no-changes --no-restore
      - run: dotnet list package --vulnerable --include-transitive
      - run: dotnet list package --outdated

